[package]
name = "arrayvec"
version = "0.4.11"
authors = ["bluss"]
license = "MIT/Apache-2.0"

description = "A vector with fixed capacity, backed by an array (it can be stored on the stack too). Implements fixed capacity ArrayVec and ArrayString."
documentation = "https://docs.rs/arrayvec/"
repository = "https://github.com/bluss/arrayvec"

keywords = ["stack", "vector", "array", "data-structure", "no_std"]
categories = ["data-structures", "no-std"]

[build-dependencies]

[dependencies]
sgx_tstd = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }


[dependencies.serde]
optional = true
version = "1.0"
git = "https://github.com/mesalock-linux/serde-sgx"

#[dependencies.serde]
#version = "1.0"
#optional = true
#default-features = false

[dev-dependencies.serde_test]
version = "1.0"

[dev-dependencies]
matches = { version = "0.1" }
bencher = "0.1.4"

[[bench]]
name = "extend"
harness = false

[[bench]]
name = "arraystring"
harness = false

[features]
default = ["std","mesalock_sgx"]
std = []
serde-1 = ["serde"]
mesalock_sgx = ["std","sgx_tstd"]
array-sizes-33-128 = []
array-sizes-129-255 = []

[package.metadata.docs.rs]
features = ["serde-1"]

[package.metadata.release]
no-dev-version = true
